### PR TITLE
Fixes for oss-fuzz:556440

### PR DESCRIPTION
**Pull request by AshwinNatesan-ittiam**
Fixes for bug-556440

### CODE REVIEW

**Review by harishdm — CHANGES_REQUESTED** [review]
Can you please update the commit message as below

Title
<empty line>
Body

BUG=oss-fuzz:55640
Test: svc_enc_fuzzer

**Comment by AshwinNatesan-ittiam** [comment]
I force pushed the amended commit. Is this the mechanism to be used for updating PR's?

**Comment by harishdm** [comment]
> I force pushed the amended commit. Is this the mechanism to be used for updating PR's?

no, this isn't a mechanism to be followed when the commit actually changes. a follow up CL in the same pull request is the recommended way.

**Review by harishdm — APPROVED** [review]

**Comment by harishdm** [comment]
> Can you please update the commit message as below
> 
> Title Body
> 
> BUG=oss-fuzz:55640 Test: svc_enc_fuzzer

done.

**Pull request merged**
